title: John Doe
subtitle: Full Stack Web Developer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll - A Jekyll Theme Built For Developers

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devlopr.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

disqus_shortname: sujay-kundu  #for comments using disqus

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Contact Me
      url : /contact/
    - text: Styleguide
      url: /styleguide/



# Edit these details 

author_logo: profile.png
author: John Doe
author_bio: Hi, My Name is John Doe. I love to Code and Design. 
author_email: "johndoe@gmail.com"
author_location: India
author_website_url: "http://johndoe.com"

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

# social links
twitter_username: 
github_username:  johndoe
facebook_username: johndoe
linkedin_username: johndoe
behance_username: johndoe
instagram_username: johndoe
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe

markdown: kramdown

google_analytics: UA-46783401-10 # Google Analytics Code 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate: 8
per_page: 4
paginate_path: "/page/:num/"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']



